extends:
  - semantic-release-preconfigured-conventional-commits
plugins:
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  -
    - "@semantic-release/exec"
    - publishCmd: |
        git tag -a -f ${nextRelease.version} ${nextRelease.version} -F CHANGELOG.md
        git push --force origin ${nextRelease.version}
        ./gradlew releaseJavaMavenOnMavenCentralNexus --parallel || exit 1
  -
    - "@semantic-release/github"
    - "assets":
      - "path": "build/shadow/*-all.jar"
  - "@semantic-release/git"
